# {{item}} is an entrynode ansible host
- set_fact:
    tinc_net_dir: "{{hostvars[item].get('tinc_boot_tinc_dir', '/etc/tinc')}}/{{hostvars[item].get('tinc_boot_network', tinc_boot_network)}}"
- name: "create buffer for keys"
  tempfile:
    suffix: keys
    state: directory
  register: "buffer"
- name: "copy nodes keys from {{item}} to local buffer"
  synchronize:
    mode: pull
    src: "{{tinc_net_dir}}/hosts/"
    dest: "{{buffer.path}}/"
- name: "copy {{item}} keys to {{ansible_hostname}}"
  synchronize:
    mode: push
    src: "{{buffer.path}}/"
    dest: "{{tinc_boot_tinc_dir}}/{{tinc_boot_network}}/hosts/"
- name: "detect public nodes"
  find:
    paths: "{{buffer.path}}"
    contains: "Address"
  register: "public_nodes"
- name: "add records to configuration"
  lineinfile:
    path: "{{tinc_boot_tinc_dir}}/{{tinc_boot_network}}/tinc.conf"
    regexp: "ConnectTo[ ]*=[ ]*{{item.path | basename}}"
    line: "ConnectTo = {{item.path | basename}}"
  loop: "{{public_nodes.files}}"
- name: "clean buffer"
  file:
    state: absent
    path: "{{buffer.path}}"
- name: "push own key to {{item}}"
  copy:
    src: "{{tinc_boot_tinc_dir}}/{{tinc_boot_network}}/hosts/{{tinc_boot_name}}"
    dest: "{{tinc_net_dir}}/hosts/{{tinc_boot_name}}"
    mode: a+x
  delegate_to: "{{item}}"
